class Commons {
    static USER_NAME = "USER_NAME";
    static DESCENDING = "Descending";
    static EMPLOYEE_NAME = "EMPLOYEE_NAME";
    static IS_OPEN = "is-open";
    static IS_ACTIVE = "is-active";
    static EMPLOYEE_ID = "EMPLOYEE_ID";
    static CLOSED = "closed";
    static APPLICATIONS = "Applications";
    static WORKSPACES = "Workspaces";
    static VENDOR_NUMBER = "VENDOR_NUMBER";
    static ITEM_NUMBER = "ITEM_NUMBER";
    static BASE_URL = "BASE_URL";
    static V2 = "/v2/";
    static PASSWORD = "PASSWORD";
    static INSTRUCTOR = "INSTRUCTOR";
    static STUDENT_NAME = "STUDENT_NAME";
    static WEBMAIL = "WebMail";
    static USEFUL_LINKS = "Useful Links";
    static DOWNLOAD = "Download";
    static AS_PDF = "As PDF";
    static BOOKMARKS = "Bookmarks";
    static DOWNLOAD_AS_PDF = "Download as PDF";
    static DOCUMENT_TYPE = "Document Type";
    static QMS_DOCUMENT_TYPE = "QMS";
    static LOGISTIC_COMPANY = "LOGISTIC_COMPANY";
    static FINANCIAL_COMPANY = "FINANCIAL_COMPANY";
    static CITY = "CITY";
    static STATE = "STATE";
    static CITY_BSI_CODE = "CITY_BSI_CODE";
    static NEXT_EMPLOYEE_ID = "NEXT_EMPLOYEE_ID";
    static INSTRUCTOR_NAME = "INSTRUCTOR_NAME";
    static R = "R";
    static EMPLOYEE = "EMPLOYEE";
    static USER_HOME = "user.home";
    static ASSIGN_TO_ME = "Assign to me";
    static APPROVE = "Approve";
    static PO_ID = "PO ID";
    static PO_SUP_NAME = "PO Sup Name";
    static DONE = "Done";
    static VIEW_PO_DOCUMENT = "View PO Document";
    static CONTENT_ADMINISTRATOR = "CONTENT_ADMINISTRATOR";
    static EMAIL = "EMAIL";
    static MENTEE = "MENTEE";
}

export default Commons;