class Workflows_Id {
  static NAME = "wfNameTextBox";
  static DESCRIPTION = "wfDescriptionTextArea";
  static FILTER_SEARCH = "filterTextBox";
  static ADD_PARAMETER = "addParameterButton";
  static PARAMETER_NAME = "parameterNameTextBox";
  static INPUT_CHK = "parameterInput";
  static OUTPUT_CHK = "parameterOutput";
  static USE_INITIAL_VALUE_IF_NULL_CHK = "parameterUseInitialvalueIfNull";
  static INITIAL_VALUE = "parameterInitialStringValue";
  static SEARCH = "searchButton";
  static ADD_DRILL_BACKS = "addDrillBacksButton";
  static NAME_DRILLBACK = "Error";
  static LOGICAL_ID_RDN = "ViewParameterMapping";
  static PID_RDN = "ViewParameterMapping";
  static ADD_DECISION_PROPERTIES = "addConditionButton";
  static NAME_DECISION_PROPERTIES = "conditionNameTextBox";
  static TASK_NAME = "taskNameTextBox";
  static MESSAGE = "defaultTranslationTextBox";
  static TASK_DESCRIPTION = "taskDescriptionTextBox";
  static ADD_TASK_PROPERTIES = "addContentButton";
  static USE_CUSTOM_ACTION_BUTTONS_TO_SET_PARAMETR_RDN = "actionTypeCustomRadioButton";
  static ADD_ACTION = "addActionButton";
  static VALUE_GRID = "dataGridLastColumn";
  static BUTTON_LABEL_GRID = "cellWithoutRightBorder";
  static ADVANCED_RDN = "distributionListAdvancedRadioButton";
  static EDIT_CONDITION = "Edit Condition";
  static EDIT_DISTRIBUTION = "Edit Distribution";
  static SEARCH_DISTRIBUTION = "distributionDialogSearchTextBox";
  static DEFAULT_DISTRIBUTION_WHEN_NONE_OF_THE_CONDITIONS_IS_SATISFIED_CHK = "defaultDistributionCheckBox";
  static USER = "defaultDistributionIdentifier";
  static USE_CUSTOM_ACTION_BUTTON_DONE_RDN = "actionTypeStandardRadioButton";
  static TASK_NAME_SET_PARAMETER = "nameTextBox";
  static SET_PARAMETER_VALUE = "parameterInitialStringValue";
  static NAME_NOTIFICATION = "notiicationNameTextBox";
  static MESSAGE_NOTIFICATION = "defaultTranslationTextBox";
  static EXPIRES_AFTER_CHK = "lifetimeCheckBox";
  static TASK_1 = "Task_1";
  static UP_ACTION = "moveUpContentButton";
  static NOTIFICATION_ERROR = "errorsCountLabel";
  static PARAMETER_DECISION_PROPERTIES_DRP = "attributeListDropDown";
  static OPERATOR_DRP = "comparisionOperatorList";
  static ADD_DISTRIBUTION = "addDistributionButton";
  static DISTRIBUTION_TYPE_DRP = "distributionTypeListDropDown";
}

export default Workflows_Id;